plugins:
  - jemoji
  - jekyll-relative-links
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - "*.md"
  - "Andromeda-Apps/*.d"
  - "fnt/*.md"
  - "HBoot/*.md"
  - "Hexagon/*.md"
  - "Hexagonix/*.md"
  - "HX/*.md"
  - "lib/*.md"
  - "Unix-Apps/*.md"
  - LICENSE
  - "LICENSES/"
name: ""
title: null
permalink: pretty
