plugins:
  - jemoji
  - jekyll-relative-links
markdown: GFM
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - "*.md"
  - LICENSE
  - "LICENSES/"
name: ""
title: null
permalink: pretty
