plugins:
  - jemoji
  - jekyll-relative-links
  - jekyll-github-metadata
markdown: GFM
permalink: pretty
relative_links:
  enabled: true
  collections: false
name: ""
title: null
gems:
  - jekyll-relative-links